AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Sensors Stream SAM Application.
  Defines Lambda functions (zip + container image) for ALB integration.

Parameters:
  ALBStackName:
    Type: String
    Description: Name of the CloudFormation stack that exports the Lambda target group ARN
    Default: alb-lambda
  CognitoUserPoolId:
    Type: String
    Description: ID of the Cognito user pool
    Default: il-central-1_0zf0LNlSD
  CognitoUserPoolClientId:
    Type: String
    Description: ID of the Cognito user pool client
    Default: 2chpfairj5rakt9lffar3gnv3h
  DynamoDBSensorParametersTableName:
    Type: String
    Description: Name of the DynamoDB table for sensor parameters
    Default: sensor-parameters

Globals:
  Function:
    Timeout: 30
    Architectures:
      - x86_64

Resources:
  SensorsIngressTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: sns-sensors-ingress

  SensorsAverageTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: sns-sensors-average

  SensorsAbnormalLowTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: sns-sensors-abnormal-lo

  SensorsAbnormalHighTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: sns-sensors-abnormal-hi

  SensorParametersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBSensorParametersTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: sensor_id
          AttributeType: S
      KeySchema:
        - AttributeName: sensor_id
          KeyType: HASH

  HelpersLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: helpers
      Description: Shared Python helpers
      ContentUri: layers/helpers
      CompatibleRuntimes:
        - python3.12

  SensorsIngressFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: .
      Dockerfile: functions/sensors-ingress/Dockerfile
      DockerTag: python3.12
    Properties:
      PackageType: Image
      FunctionName: sensors-ingress
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref SensorsIngressTopic # pass topic ARN
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          COGNITO_USER_POOL_CLIENT_ID: !Ref CognitoUserPoolClientId
          DEBUG_LEVEL: DEBUG
      Policies:
        - Statement:
            - Effect: Allow
              Action: sns:Publish
              Resource: !Ref SensorsIngressTopic
      ReservedConcurrentExecutions: 10

  # Permission for ALB to invoke the Lambda function
  SensorsIngressInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SensorsIngressFunction
      Action: lambda:InvokeFunction
      Principal: elasticloadbalancing.amazonaws.com
      SourceArn:
        Fn::ImportValue: !Sub "${ALBStackName}-LambdaTargetGroupArn"

  # Lambda function for calculating sensor averages
  SensorsAvgFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: .
      Dockerfile: functions/sensors-avg-lambda/Dockerfile
      DockerTag: python3.12
    Properties:
      PackageType: Image
      FunctionName: sensors-avg-lambda
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref SensorsAverageTopic
          SENSOR_PARAMETERS_TABLE_NAME: !Ref DynamoDBSensorParametersTableName
          DEBUG_LEVEL: DEBUG
      Policies:
        - Statement:
            - Effect: Allow
              Action: sns:Publish
              Resource: !Ref SensorsAverageTopic
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:BatchGetItem
              Resource: !GetAtt SensorParametersTable.Arn
      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Topic: !Ref SensorsIngressTopic
      ReservedConcurrentExecutions: 10

  # Lambda function for detecting abnormal sensor data
  SensorsAbnormalFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: .
      Dockerfile: functions/sensors-abnormal-lambda/Dockerfile
      DockerTag: python3.12
    Properties:
      PackageType: Image
      FunctionName: sensors-abnormal-lambda
      Environment:
        Variables:
          SNS_ABNORMAL_LOW_TOPIC_ARN: !Ref SensorsAbnormalLowTopic
          SNS_ABNORMAL_HIGH_TOPIC_ARN: !Ref SensorsAbnormalHighTopic
          SENSOR_PARAMETERS_TABLE_NAME: !Ref DynamoDBSensorParametersTableName
          DEBUG_LEVEL: DEBUG
      Policies:
        - Statement:
            - Effect: Allow
              Action: sns:Publish
              Resource: !Ref SensorsAbnormalLowTopic
        - Statement:
            - Effect: Allow
              Action: sns:Publish
              Resource: !Ref SensorsAbnormalHighTopic
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:BatchGetItem
              Resource: !GetAtt SensorParametersTable.Arn
      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Topic: !Ref SensorsIngressTopic
      ReservedConcurrentExecutions: 10

  # Lambda-backed custom resource to register/deregister Lambda target with ALB target group
  RegisterTargetFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: stack_resources/sensors-tg-register
      Dockerfile: Dockerfile
      DockerTag: python3.12
    Properties:
      FunctionName: !Sub "${AWS::StackName}-register-target"
      PackageType: Image
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - elasticloadbalancing:RegisterTargets
                - elasticloadbalancing:DeregisterTargets
              Resource: "*"

  SensorsIngressTargetGroupAttachment:
    Type: Custom::TargetGroupAttachment
    DependsOn:
      - SensorsIngressInvokePermission
    Properties:
      ServiceToken: !GetAtt RegisterTargetFunction.Arn
      TargetGroupArn:
        Fn::ImportValue: !Sub "${ALBStackName}-LambdaTargetGroupArn"
      TargetId: !GetAtt SensorsIngressFunction.Arn

  # Lambda-backed custom resource to seed the DynamoDB sensor parameters table
  SeedSensorParamsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: stack_resources/seed-sensor-params
      Dockerfile: Dockerfile
      DockerTag: python3.12
    Properties:
      FunctionName: !Sub "${AWS::StackName}-seed-sensor-params"
      PackageType: Image
      Timeout: 60
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBSensorParametersTableName
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Query
                - dynamodb:Scan
              Resource: !GetAtt SensorParametersTable.Arn

  SeedSensorParamsInvocation:
    Type: Custom::SeedSensorParams
    DependsOn:
      - SensorParametersTable
    Properties:
      ServiceToken: !GetAtt SeedSensorParamsFunction.Arn

Outputs:
  SensorsIngressFunctionArn:
    Description: ARN of the sensors-ingress Lambda function
    Value: !GetAtt SensorsIngressFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SensorsIngressFunctionArn"

  SensorsIngressFunctionConsoleUrl:
    Description: URL to open the sensors-ingress Lambda in AWS Console
    Value: !Sub "https://console.aws.amazon.com/lambda/home?region=${AWS::Region}#/functions/${SensorsIngressFunction}"

  SensorsIngressTopicArn:
    Description: ARN of the sns-sensors-ingress SNS topic
    Value: !Ref SensorsIngressTopic
    Export:
      Name: !Sub "${AWS::StackName}-SensorsIngressTopicArn"

  SensorsAverageTopicArn:
    Description: ARN of the sns-sensors-average SNS topic
    Value: !Ref SensorsAverageTopic
    Export:
      Name: !Sub "${AWS::StackName}-SensorsAverageTopicArn"

  SensorsAbnormalTopicArn:
    Description: ARN of the sns-sensors-abnormal-low SNS topic
    Value: !Ref SensorsAbnormalLowTopic
    Export:
      Name: !Sub "${AWS::StackName}-SensorsAbnormalLowTopicArn"

  SensorsAbnormalHighTopicArn:
    Description: ARN of the sns-sensors-abnormal-high SNS topic
    Value: !Ref SensorsAbnormalHighTopic
    Export:
      Name: !Sub "${AWS::StackName}-SensorsAbnormalHighTopicArn"

  SensorsAvgFunctionArn:
    Description: ARN of the sensors-avg-lambda function
    Value: !GetAtt SensorsAvgFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SensorsAvgFunctionArn"

  SensorsAbnormalFunctionArn:
    Description: ARN of the sensors-abnormal-lambda function
    Value: !GetAtt SensorsAbnormalFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SensorsAbnormalFunctionArn"

  SensorParametersTableArn:
    Description: ARN of the DynamoDB sensor parameters table
    Value: !GetAtt SensorParametersTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SensorParametersTableArn"

  SensorParametersTableName:
    Description: Name of the DynamoDB sensor parameters table
    Value: !Ref SensorParametersTable
    Export:
      Name: !Sub "${AWS::StackName}-SensorParametersTableName"
