AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Sensors Stream SAM Application.
  Defines Lambda functions (zip + container image) for ALB integration.

Parameters:
  ALBStackName:
    Type: String
    Description: Name of the CloudFormation stack that exports the Lambda target group ARN
    Default: alb-lambda
  CognitoUserPoolId:
    Type: String
    Description: ID of the Cognito user pool
    Default: il-central-1_0zf0LNlSD
  CognitoUserPoolClientId:
    Type: String
    Description: ID of the Cognito user pool client
    Default: 2chpfairj5rakt9lffar3gnv3h

Globals:
  Function:
    Timeout: 30
    Architectures:
      - x86_64

Resources:
  SensorsIngressTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: sensors-ingress-topic

  HelpersLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: helpers
      Description: Shared Python helpers
      ContentUri: layers/helpers
      CompatibleRuntimes:
        - python3.12

  SensorsIngressFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      PackageType: Zip
      FunctionName: sensors-ingress
      Handler: app.lambda_handler
      CodeUri: functions/sensors-ingress/src
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref SensorsIngressTopic # pass topic ARN
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          COGNITO_USER_POOL_CLIENT_ID: !Ref CognitoUserPoolClientId
          DEBUG_LEVEL: DEBUG
      Policies:
        - Statement:
            - Effect: Allow
              Action: sns:Publish
              Resource: !Ref SensorsIngressTopic
      Layers:
        - !Ref HelpersLayer
      ReservedConcurrentExecutions: 10

  # Permission for ALB to invoke the Lambda function
  SensorsIngressInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SensorsIngressFunction
      Action: lambda:InvokeFunction
      Principal: elasticloadbalancing.amazonaws.com
      SourceArn:
        Fn::ImportValue: !Sub "${ALBStackName}-LambdaTargetGroupArn"

  # Lambda-backed custom resource to register/deregister Lambda target with ALB target group
  RegisterTargetFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerContext: functions/sensors-tg-register
      Dockerfile: Dockerfile
      DockerTag: python3.12
    Properties:
      FunctionName: !Sub "${AWS::StackName}-register-target"
      PackageType: Image
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - elasticloadbalancing:RegisterTargets
                - elasticloadbalancing:DeregisterTargets
              Resource: "*"

  SensorsIngressTargetGroupAttachment:
    Type: Custom::TargetGroupAttachment
    DependsOn:
      - SensorsIngressInvokePermission
    Properties:
      ServiceToken: !GetAtt RegisterTargetFunction.Arn
      TargetGroupArn:
        Fn::ImportValue: !Sub "${ALBStackName}-LambdaTargetGroupArn"
      TargetId: !GetAtt SensorsIngressFunction.Arn

Outputs:
  SensorsIngressFunctionArn:
    Description: ARN of the sensors-ingress Lambda function
    Value: !GetAtt SensorsIngressFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-SensorsIngressFunctionArn"

  SensorsIngressFunctionConsoleUrl:
    Description: URL to open the sensors-ingress Lambda in AWS Console
    Value: !Sub "https://console.aws.amazon.com/lambda/home?region=${AWS::Region}#/functions/${SensorsIngressFunction}"
